# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1ca43cad8f8d579c1e75deddb62c728b1e5063b8b392b99352e36f6f154ec489d891c07ceb87546ce7a45470011ad50b703e44d959079eb24592a72e58aab7
  facebook_app_id: <%= ENV["YELP_FB_APP_ID"] %>
  facebook_app_secret: <%= ENV["YELP_APP_SECRET"] %>

test:
  secret_key_base: 1b36bc0a0112fcc008466868c96f7b0b60ec9a69bb932f243ec770906aafdd95e9c3967a2afbfb739cb24bf32c6b47de1e87ce643275c488e092f07b6e400f18
  facebook_app_id: <%= ENV["YELP_FB_APP_ID"] %>
  facebook_app_secret: <%= ENV["YELP_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["YELP_FB_APP_ID"] %>
  facebook_app_secret: <%= ENV["YELP_APP_SECRET"] %>

